### ISSUE TITLE
fix : avoid false positiv message with `_PACKAGE` documentation during `find_missing_tags()`

### ISSUE THREAD

**Issue by VincentGuyader** [ThinkR-open/checkhelper#42] opened 2023-01-18 10:55 UTC
## validation

- [ ] The message does not appears for documentations `_PACKAGE`
- [ ] The message does not appear if I run `usethis::use_package_doc()` on my package before.

## tech 

- Create a unit test that runs `usethis::use_package_doc()`  on the example package, and make sure the outputs of `find_missing_tags()` are empty

![image](https://user-images.githubusercontent.com/10470699/213153453-b60659b6-26cd-46bc-b0f0-803c7a5c7cef.png)

we dont need to do this for this kind of file

**Comment by ArthurData** [comment] 2023-02-20 16:26
Close to #70

**Comment by ArthurData** [comment] 2023-03-29 09:52
This is is a duplicate of #70

**Closed** 2023-03-29 09:52 UTC
Labels: duplicate
